# Generated by Django 3.2.4 on 2021-07-08 19:39
import uuid
from django.db import migrations, models
from blog.models import Post

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_slug'),
    ]

    def gen_uuid(apps, schema_editor):
        for row in Post.objects.all():
            row.slug = uuid.uuid4()
            row.save()

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=200),
            preserve_default=True,
        ),
        migrations.RunPython(gen_uuid),

        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
