# Generated by Django 3.2.4 on 2021-07-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='DEFAULT VALUE', max_length=200, unique=True),
        ),
    ]
